### ISSUE TITLE
请教Robot的证书问题

### ISSUE THREAD

**Issue by BreezeZhang** [lwch/QQRobot#1]
请问下，你perms文件夹下的证书是怎么颁布的呢，非常谢谢！

**Comment by lwch** [comment]
从webqq的网站上下的

**Comment by BreezeZhang** [comment]
是在打开webqq网站时，从浏览器导出的证书私钥么。。。
你那程序str struct结构写的很赞，很有收获,谢谢哈

**Comment by xidianby0911** [comment]
你好，请问一下代码的运行平台是什么，我在Linux和VS上运行时，都提示缺少库文件，#include <auto_config.h>#include <auto_module.h>这些库文件从哪里弄啊
