### ISSUE TITLE
你的Robot是基于web3.0的么

### ISSUE THREAD

**Issue by BreezeZhang** [lwch/QQRobot#2]

**Comment by lwch** [comment]
是的，这只是一个玩具。。

**Comment by BreezeZhang** [comment]
恩  对你来说确实只是个玩具

**Comment by BreezeZhang** [comment]
嗨嗨 又打扰了。。。不过昨晚上搞到两点多，才迫不得已的。。。原谅我吧！！！
请教下，貌似pems下的密钥 ，只有本人电脑重新生成，不能直接在我的上面用吧
如果是我自己的电脑，我把证书转换成密钥的时候，只能生成公钥和私钥
https 貌似是不是 只用使用自己一个私钥就行了啊，为什么你的里面三个啊
怎么生成的呢，，

**Comment by lwch** [comment]
我这底下都是腾讯颁发的证书

**Comment by BreezeZhang** [comment]
灰常谢谢哈
